site :opscode


# cookbook 'apt', '2.3.8'
# cookbook 'aws', '0.101.6'
# cookbook 'erlang'
# cookbook 'memcached', '1.6.0'
# cookbook 'build-essential'
# cookbook 'nginx'
# cookbook 'haproxy'
# cookbook 'apache2'
cookbook 'database'
cookbook 'haproxy', github: 'cstewart87/haproxy', branch: 'rhel_init'
cookbook 'apache2', github: 'mattray/apache2', branch: 'DefaultType'
cookbook 'mysql'
cookbook 'sudo'
cookbook 'users'

cookbook 'demo-app', path: './cookbooks/demo-app'
# cookbook 'openstack-block-storage', github: 'stackforge/cookbook-openstack-block-storage'
# cookbook 'openstack-common', github: 'stackforge/cookbook-openstack-common'
# cookbook 'openstack-compute', github: 'stackforge/cookbook-openstack-compute'
# cookbook 'openstack-dashboard', github: 'stackforge/cookbook-openstack-dashboard'
# cookbook 'openstack-identity', github: 'stackforge/cookbook-openstack-identity'
# cookbook 'openstack-image', github: 'stackforge/cookbook-openstack-image'
# cookbook 'openstack-network', github: 'stackforge/cookbook-openstack-network'
# cookbook 'openstack-object-storage', github: 'stackforge/cookbook-openstack-object-storage'
# cookbook 'openstack-ops-database', github: 'stackforge/cookbook-openstack-ops-database'
# cookbook 'openstack-ops-messaging', github: 'stackforge/cookbook-openstack-ops-messaging'
# cookbook 'openstack-orchestration', github: 'stackforge/cookbook-openstack-orchestration'
# cookbook 'openstack-telemetry', github: 'stackforge/cookbook-openstack-telemetry'
